# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Zubi.ZubiSniffer
PackageVersion: 2.1.0
PackageLocale: en-US
Publisher: Zubi
PackageName: ZubiSniffer
License: GPL-3.0
Copyright: GNU GPLv3 - built using the open-source Session Sniffer project by BUZZARDGTA and contributors
ShortDescription: Windows desktop packet and session sniffer with live endpoint visibility and manual IP organization.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
