# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zubi.ZubiSniffer
PackageVersion: 2.1.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mhemaamnimmer-stack/zubisniffer/releases/download/v2.1.0/ZubiSniffer-Setup.exe
  InstallerSha256: DBF7E465DCD44FA77D058BAF8502685F7BC075255224F80887B729B6719AE0DF
ManifestType: installer
ManifestVersion: 1.12.0
